config/routes.rb
Orderapp::Application.routes.draw do
  
  resources :orders

  resources :restaurants

  devise_for :admins
  devise_for :users

  root 'orders#new'
  get 'restaurants' => 'restaurants#index'
  get 'today' => 'orders#today'

  

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id              :integer          not null, primary key
#  content         :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  user_id         :integer
#  restaurant_name :string(255)
#

class Order < ActiveRecord::Base

	belongs_to :user
	has_one :restaurant

	default_scope :order => 'orders.created_at DESC'

	def order_params
      params.require(:order).permit(:content, :restaurant_name)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def today
    @orders = Order.all
    @restName = @orders.first.restaurant_name
    @todayIs = Date.today
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @restName = @orders.first.restaurant_name
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    
    if user_signed_in?

      @orders = Order.all
      
      @order = current_user.orders.new

        # logic to determine the day of week, then present it in human-readable format
        todayIs = Date.today.wday
        days = [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" ]
        @whatDay = days[todayIs]

        # take the day from above and lookup and print the restaurant
        @todaysRestaurant = Restaurant.find_by day: @whatDay
        @restName = @todaysRestaurant.name
        @restID = @todaysRestaurant.id
        @menuURL = @todaysRestaurant.menu_link

    end

  end

  # GET /orders/1/edit
  def edit

        # logic to determine the day of week, then present it in human-readable format
        todayIs = Date.today.wday
        days = [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" ]
        @whatDay = days[todayIs]

        # take the day from above and lookup and print the restaurant
        @todaysRestaurant = Restaurant.find_by day: @whatDay
        @restName = @todaysRestaurant.name
        @restID = @todaysRestaurant.id
        @menuURL = @todaysRestaurant.menu_link
 
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update

    @order = current_user.orders.find(params[:id])

    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    
    @order = current_user.orders.find(params[:id])

    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:content, :restaurant_name)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

	def findEmail(order)
		thisUser = User.where(id: order.user_id )
		@thisOrder = thisUser.first.email
	end
end

app/views/orders/_form.html.erb
<% if user_signed_in? %>

  <p>Today is <%= @whatDay %></p>
  <p>Order from <strong><%= @restName %></strong>: <%= link_to "view menu", @menuURL, :target => "_blank", :class => "btn" %></p>

  <%= simple_form_for(@order, html: { class: ""} ) do |f| %>
    <%= f.error_notification %>
    <%= f.input :content, as: :text, label: "What would you like?", input_html: { rows: "3"} %>
    <%= f.input :restaurant_name, :as => :hidden, :input_html => { :value => @restName } %>
    
    <div class="form-actions">
      <%= f.button :submit, value: "Place Order", class: "btn btn-primary" %>
    </div>
  <% end %>

  <% else #if they're not logged in, show this %>
   
  <p><%= link_to "Please sign in to place an order.", new_user_session_path, class: "btn btn-large" %></p>
  <p><%= link_to "Signup Now", new_user_registration_path, class: "btn" %><i>  you must be signed in to place an order</i></p>

<%end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>All Orders</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date Ordered</th>
      <% if admin_signed_in? %> 
        <th>Ordered by</th> 
      <% end %>
      <th>Order Content</th>
      <th>Edit Order</th>
      <th>Cancel Order</th>
    </tr>
  </thead>

  <tbody>

    <% if admin_signed_in? %> 
      <% @orders.each do |order| %>
          <tr>
            <td><%= order.created_at.strftime("%m/%d/%y") %></td>
            <td>
                <% thisUser = User.where(id: order.user_id ) %>
                <%= thisUser.first.email %>
            </td>
            <td><%= order.content %></td>
            <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Cancel', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %> 
    <% end %> 

    <% if user_signed_in?%> 
      <% current_user.orders.find(params[:id]) do |order| %>
        <tr>
          <td><%= order.created_at.strftime("%m/%d/%y") %></td>
          <td><%= order.content %></td>
          <td><%= link_to 'Edit', edit_order_path(order) %></td>
          <td><%= link_to 'Cancel', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %> 
    <% end %> 

  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>Place a lunch order</h1>

<%= render 'form' %>

<% if user_signed_in?%> 
	<table class="table table-striped table-bordered">
	  <thead>
	    <tr>
	    	<th width=120> </th>
	      <th>Previous Orders from <%= @restName %></th>
	    </tr>
	  </thead>
		<tbody>
		  <% current_user.orders.where( restaurant_name: @restName ).each do |order| %>
		    <tr>
		      <td>click to reorder</td>
		      <td><%= order.content %></td>
		    </tr>
		  <% end %> 	
		</tbody>
	</table>
<% end %> 

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @order.content %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/today.html.erb
<h1>Today's Orders</h1>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date Ordered</th>
      <th>Ordered From</th>
      <th>Ordered by</th> 
      <th>Order Content</th>
      <th>Edit Order</th>
      <th>Cancel Order</th>
    </tr>
  </thead>

  <tbody>

    <% if admin_signed_in? %> 
      <% @orders.where( "created_at >?", @todayIs ).each do |order| %>
          <tr>
            <td><%= order.created_at.strftime("%m/%d/%y") %></td>
            <td><%= @restName %></td>
            <td>
                <% thisUser = User.where(id: order.user_id ) %>
                <%= thisUser.first.email %>
            </td>
            <td><%= order.content %></td>
            <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Cancel', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %> 
    <% end %> 
  </tbody>
</table>

<br>

<% if user_signed_in?%> 

  <%= link_to 'Place New Order', new_order_path, class: "btn" %>

<% end %>