config/routes.rb
Orderapp::Application.routes.draw do
  
  resources :orders

  resources :restaurants

  devise_for :admins
  devise_for :users

  root 'orders#new'
  get 'restaurants' => 'restaurants#index'
  get 'today' => 'orders#today'

  

end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  menu_link  :string(255)
#  home_link  :string(255)
#  day        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Restaurant < ActiveRecord::Base
	validates :name, presence: true
	validates :menu_link, presence: true
	validates :home_link, presence: true
	validates :day, presence: true,
			  :uniqueness => true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :menu_link, :home_link, :day)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant, html: { class: "form-horizontal"} ) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: "Restaurnt Name" %>
  <%= f.input :home_link, label: "URL of restaurnt's website" %>
  <%= f.input :menu_link, label: "URL of menu" %>
  <%= f.input :day, collection: [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" ], label: "What day is this restaurant available?" %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<% if admin_signed_in? %>

  <h1>Listing restaurants</h1>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Menu link</th>
        <th>Home link</th>
        <th>Day</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= restaurant.name %></td>
          <td><%= restaurant.menu_link %></td>
          <td><%= restaurant.home_link %></td>
          <td><%= restaurant.day %></td>
          <td><%= link_to 'Show', restaurant %></td>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add a New Restaurant', new_restaurant_path, class: "btn" %>

<% else %>

  <p><%= link_to "Place and order", new_order_path, class: "btn" %></p>

<% end %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Menu link:</strong>
  <%= @restaurant.menu_link %>
</p>

<p>
  <strong>Home link:</strong>
  <%= @restaurant.home_link %>
</p>

<p>
  <strong>Day:</strong>
  <%= @restaurant.day %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>