config/routes.rb
Orderapp::Application.routes.draw do
  
  resources :orders

  resources :restaurants

  devise_for :admins
  devise_for :users

  root 'orders#new'
  get 'restaurants' => 'restaurants#index'
  get 'today' => 'orders#today'

  

end

app/views/layouts/_footer.html.erb
<div class="footer">
	<hr />
  <small>
  	<p>copyright 2013</p>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <div class="row-fluid">
        <div class="span8 offset2">

       
            <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
       
            <!-- Be sure to leave the brand out there if you want it shown -->
            <p class="brand" >archer>malmo lunch</p>
       
            <!-- Everything you want hidden at 940px or less, place within here -->
            <div class="nav-collapse collapse">
          		<ul class="nav">
          			<li><% link_to "Home", root_path %></li>
          		</ul>

          <ul class="nav pull-right">
            
            <% if admin_signed_in? # admin nav elements %>
              <li><%= link_to "Today's Orders", today_path %></li>
              <li><%= link_to "All Orders", orders_path %></li>
              <li><%= link_to "All Restaurants", restaurants_path %></li>
              <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>

            <% else %>

              <% if !user_signed_in? # hide if User signed in %>

                <li><%= link_to "Admin Login", new_admin_session_path %></li>

              <% end %>

            <% end %> 

            <% if user_signed_in? # user nav elements %>
              <li><%= link_to "All Orders", orders_path %></li>
              <li><%= link_to "Place Order", root_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>


          </div>

      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Order Online</title>
	  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="span8 offset2">
								
					<% flash.each do |name, msg| %>
		                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		            <% end %>

					<%= yield %>			

					<%= render 'layouts/footer' %>
				</div
			</div>
		</div>
	</body>
</html>